### ISSUE TITLE
I have a few questions

### ISSUE THREAD

**Issue by lloveapple** [qcraftai/pillarnext#12]
On waymo val, I saw that the accuracy of pillarnet is like this. Why is yours so high?

![image](https://github.com/qcraftai/pillarnext/assets/48848691/0780134f-d54d-4b05-8c30-aa1f8f5c9836)

yours is this
![image](https://github.com/qcraftai/pillarnext/assets/48848691/167535bd-7c23-4d4c-bbf9-49f261ec2506)

**Comment by Konstantin5389** [comment]
The first table shows 3D mAP/mAPH, but the second table shows BEV mAP/mAPH.
