### ISSUE TITLE
how to get BEV evaluation results 

### ISSUE THREAD

**Issue by lloveapple** [qcraftai/pillarnext#14]
Hello, thank you very much for your excellent work. I would like to ask you how you obtained the evaluation results under BEV on the waymo validation set on the Waymo data set. I checked some information, but did not find a clear method to explain how Obtain BEV mAP and BEV mAPH  in Waymo Val. Thank you so much

**Comment by Konstantin5389** [comment]
https://github.com/waymo-research/waymo-open-dataset/blob/1297cdcbcd103d4befb4b498e50a0c030053e6c0/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L98
Label::Box::TYPE_3D -> Label::Box::TYPE_2D
