### ISSUE TITLE
Meaning of dist. 

### ISSUE THREAD

**Issue by NariaPetrova** [qcraftai/pillarnext#18]
hello @Konstantin5389 ,  there're some plots in output folder, could you pls expain the meaning of dist_pr_0.5/1.0./2.0/4.0? Have no idea  about the abbreviation **Dist.** , is that distance?. Thanks.

**Comment by Konstantin5389** [comment]
please refer to nuscenes offical documents. actually, it's distance, nuscenes use distance to judge whether a object is positive instance.
