### ISSUE TITLE
Memory Requirements - Reg

### ISSUE THREAD

**Issue by jyothsna-phd22** [qcraftai/pillarnext#19]
Hi, 
I am working on nuscenes lidar-only dataset for object detection. Can you please address my question regarding the memory Requirement to work on nuscenes full dataset?

Right now, we have a nvidia GeForce RTX 4080 system each with 32GB RAM, 16GB dedicated GPU and 9728 CUDA cores. Can I work on Nuscenes lidar-only full dataset with this specification?

**Comment by Konstantin5389** [comment]
a single 4080 is enough for inference but it may require unacceptable long time to train a model
