### ISSUE TITLE
waymo data code is not work

### ISSUE THREAD

**Issue by nobug-code** [qcraftai/pillarnext#2]
Can u check ure code?

**Comment by Konstantin5389** [comment]
We have checked the latest code and it works. Could you please provide the details so that we can try to solve problems for you?

**Comment by qzhang-nuro** [comment]
Hi @Konstantin5389 I have some related questions
1 - which [version](https://waymo.com/open/download/) of WOD was used for the scope of this paper?
2 - I tried downloading just a few tfrecords from [v1.4.1](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_4_1/individual_files?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) and organized them as [instructed](https://github.com/qcraftai/pillarnext/blob/main/docs/DATA.md). When I run `python tools/create_data.py waymo_data_prep` I get the following error:
```
  File "/home/pillarnext/det3d/datasets/waymo/waymo_convert.py", line 143, in convert
    fname = scenes[idx]
NameError: name 'scenes' is not defined
```
and if I replace that with `def convert(fname, save_root):`
i also get `name save_root not defined` at line 195
```
with open(os.path.join(save_root, 'waymo_infos_' + split + '.pkl'), 'wb') as f:
            pickle.dump(all_infos, f)
```
can you double check waymo_convert.py? thx!

**Comment by Konstantin5389** [comment]
Thanks for your question!
1. We use waymo 1.4.0 for this task
2. Some bugs about name defining, we have fix them. Please check commit history.
