### ISSUE TITLE
Help with Understanding PillarNext

### ISSUE THREAD

**Issue by LuizGuzzo** [qcraftai/pillarnext#20]
I'm trying to understand PillarNext, but the system has a complexity I'm not accustomed to. My questions are geared towards trying to reproduce its functionality to test detection. I'd like to know how the model receives the point clouds and converts them into coordinates to be printed on an image. For example, what needs to be done to convert a point cloud from a dataset, how to feed it into the model, and how to convert it into an image with the detections.

I'd love to know if there's any prototype or intuitive example that demonstrates this conversion of the point cloud, showing how it enters the model and how it exits. Something similar to the Waymo quickstart, which you provided in your README, showing how to visualize the dataset, would be useful for understanding PillarNext.

I'd also like to apologize for my ignorance, as I'm new to this field that uses point clouds. Additionally, if you have references to repositories for studying similar architectures that aim to solve this problem, it would be very helpful for me to delve deeper into this topic. Thank you.

**Comment by Konstantin5389** [comment]
https://github.com/qcraftai/pillarnext/blob/a9a2864089092a5f9f8ded7c3a95bafa4edbf325/det3d/models/readers/pillar_encoder.py#L174
