### ISSUE TITLE
where is the implementation of faded copy-and-paste？

### ISSUE THREAD

**Issue by aaaaannnnn11111** [qcraftai/pillarnext#3]
hi，i am really interested about the mentioned faded copy-and-paste，but i couldn‘t found out which file implements this function

**Comment by Konstantin5389** [comment]
Please refer to [pillarnext/det3d/datasets/pipelines/sample_ops.py DataBaseSamplerV2](https://github.com/qcraftai/pillarnext/blob/c0856e097e5c8f57c00db320e2fae1cb4c56f01f/det3d/datasets/pipelines/sample_ops.py#L70)
it is used in https://github.com/qcraftai/pillarnext/blob/c0856e097e5c8f57c00db320e2fae1cb4c56f01f/det3d/datasets/base.py#L73
