### ISSUE TITLE
Questions about Waymo val set results

### ISSUE THREAD

**Issue by StiphyJay** [qcraftai/pillarnext#5]
Thanks for your great work! I have one question. In your paper, the  performance of PillarNeXt-B model in one frame setting on Waymo val set is: 69.8 L2 mAPH in vehicle class
<img width="1232" alt="image" src="https://github.com/qcraftai/pillarnext/assets/28260101/48457ff5-7ec1-48c1-beac-6297c0d581c9">
However, in your github, this performance is 67.8 L2 mAPH, which one is the right results?

**Comment by Konstantin5389** [comment]
Thanks for your question! It's a typo. We have revised README. The paper results are correct.
