### ISSUE TITLE
How to run PillarNext on Kitti dataset

### ISSUE THREAD

**Issue by siddharth130500** [qcraftai/pillarnext#6]
Hi, I want to try running PillarNext on Kitti point cloud data with tracklet labels (stored in xml files). Can you suggest me how to convert Kitti data into a format like Nuscenes or Waymo open dataset which can be run on the PillarNext model?

**Comment by Konstantin5389** [comment]
You can convert all training infos in a "*.pkl" file just like nusc or WOD. And you can set up a new class KittiDataset from base dataset. Remember that the coordinates in kitti is not same with nusc and WOD.

**Comment by altogot** [comment]
> Hi, I want to try running PillarNext on Kitti point cloud data with tracklet labels (stored in xml files). Can you suggest me how to convert Kitti data into a format like Nuscenes or Waymo open dataset which can be run on the PillarNext model?

Hi, have you implemented this part of the code?

**Comment by Konstantin5389** [comment]
> > Hi, I want to try running PillarNext on Kitti point cloud data with tracklet labels (stored in xml files). Can you suggest me how to convert Kitti data into a format like Nuscenes or Waymo open dataset which can be run on the PillarNext model?
> 
> Hi, have you implemented this part of the code?

no, we have not
